ARG GO_VERSION=1.24.1
ARG DISTRO_VERSION=alpine3.21
ARG IMAGE_TAG=${GO_VERSION}-${DISTRO_VERSION}

FROM golang:${IMAGE_TAG} AS builder

RUN apk update && \
    apk add upx --no-cache

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY ./main.go .

RUN GOOS=linux CGO_ENABLED=0 go build -buildvcs=false -trimpath -ldflags="-s -w" main.go

FROM scratch AS runner

WORKDIR /app

COPY --from=builder ./build/main .

EXPOSE 3000

ENTRYPOINT ["./main"]
